version: '3.4'

services:
  Bookstore.Database:
    image: postgres

  Seq:
    image: datalust/seq:latest

  Redis:
    image: redis

  MessageBus:
    image: rabbitmq:management

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3

volumes:
  postgres_bookstoredb: